<a href="https://colab.research.google.com/github/JacobHSampson/FranklinU/blob/main/Jacob_Sampson_Assignment02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment for Week 2

## Purpose:     
This assignment is intended to help you do the following:   
1.	Modify and add information on the dataset by adding and calculating new columns     
2.	Work with dates in a dataset       
3.	Learn how to write and save your work as a csv file from Jupyter Notebook.

## Action Items:       
â€¢	Create a new column using the date column.     
  1. Find the maximum date of your data.     
  2. Subtract all the dates on the column from the maximum date.       
  3. Convert the number of days into number of months.       
  4. Save the result on a new column and add to the data set.        
  5. Save the dataset as a csv file.        
  6. Upload the assignment on your GitHub account and Update the README file where you explain everything you did.

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/frankData612/data_612/master/stock_data/stocks_yahoo.csv')
df.head()

   no         date  ... Dividend Yield 1Y target est
0   1  Nov 21 2019  ...      N/A (N/A)      1,487.52
1   2  Nov 21 2019  ...      N/A (N/A)      1,459.33
2   3  Nov 21 2019  ...   6.48 (4.86%)         148.3
3   4  Nov 21 2019  ...   2.04 (1.36%)        160.16
4   5  Nov 21 2019  ...   3.08 (1.16%)        257.21

[5 rows x 19 columns]

In [ ]:
df.dtypes

no                     int64
date                  object
company_name          object
price_at_close        object
price_change          object
price_after_hours     object
previous_close        object
today opened          object
price range           object
52 week range         object
volume                object
average volume        object
market cap            object
beta (3Y Monthly)    float64
PE Ratio              object
EPS                   object
earnings date         object
Dividend Yield        object
1Y target est         object
dtype: object

In [ ]:
date_datetime = pd.to_datetime(df['date'], infer_datetime_format=True)
date_datetime

0       2019-11-21
1       2019-11-21
2       2019-11-21
3       2019-11-21
4       2019-11-21
           ...
67900   2020-04-28
67901   2020-04-28
67902   2020-04-28
67903   2020-04-28
67904   2020-04-28
Name: date, Length: 67905, dtype: datetime64[ns]

In [ ]:
df['date_dt'] = date_datetime

df.head()

   no         date  ... 1Y target est    date_dt
0   1  Nov 21 2019  ...      1,487.52 2019-11-21
1   2  Nov 21 2019  ...      1,459.33 2019-11-21
2   3  Nov 21 2019  ...         148.3 2019-11-21
3   4  Nov 21 2019  ...        160.16 2019-11-21
4   5  Nov 21 2019  ...        257.21 2019-11-21

[5 rows x 20 columns]

In [ ]:
max_date = date_datetime.max()

In [ ]:
days = max_date - df['date_dt']
days = days.dt.days

In [ ]:
months = days/31.0
months
df['months_since_max'] = months
df

          no         date  ...    date_dt months_since_max
0          1  Nov 21 2019  ... 2019-11-21         5.129032
1          2  Nov 21 2019  ... 2019-11-21         5.129032
2          3  Nov 21 2019  ... 2019-11-21         5.129032
3          4  Nov 21 2019  ... 2019-11-21         5.129032
4          5  Nov 21 2019  ... 2019-11-21         5.129032
...      ...          ...  ...        ...              ...
67900  67901  Apr 28 2020  ... 2020-04-28         0.000000
67901  67902  Apr 28 2020  ... 2020-04-28         0.000000
67902  67903  Apr 28 2020  ... 2020-04-28         0.000000
67903  67904  Apr 28 2020  ... 2020-04-28         0.000000
67904  67905  Apr 28 2020  ... 2020-04-28         0.000000

[67905 rows x 21 columns]

In [ ]:
df.to_csv('df_clean.csv', index=False)